### ISSUE TITLE
Opening on start-up despite preference being disabled.

### ISSUE THREAD

**Issue by paulmist** [slashlos/He3#11]
I've disabled 'Auto launch at login' but the app still opens.

**Comment by slashlos** [comment]
Version info?

**Comment by paulmist** [comment]
v 1.04 from the App Store

**Comment by slashlos** [comment]
This was resolved as of build 8418, aka 1.0.4; 1.0.5 is on the app store.

**Comment by paulmist** [comment]
Just reinstalled after not using the app for a while, and this issue has returned.

App Store - 1.0.12
