### ISSUE TITLE
Netflix - dragging progress bar drags window

### ISSUE THREAD

**Issue by paulmist** [slashlos/He3#12]
Version: Latest Appstore

Dragging the progress bar while playing a video drags the entire window.

**Comment by slashlos** [comment]
While I can reproduce, the code explicitly disabling dragging; it's annoying but try the suggested workarounds.

**Comment by slashlos** [comment]
This appear to be something out of my control, having explicitly disabled this and in a prototype WkWebView [SimpleViewer](https://github.com/slashlos/SimpleViewer) exhibits same behavior in addition to stuttering UI.

The back story is that a transparent view is placed atop the view to manage drags, which I thought was intercepting drags, but appears not, at least not in the prototype. At the time it was a temporary measure so this is a work in progress. Hopefully this might get cleared out - things are always improving.

**Comment by slashlos** [comment]
Found the problem; title bar drag support via mouseDown() was complicating intra window views' drags. Fixed in build 8423.
