### ISSUE TITLE
Please provide way to change shortcut that mutes/hides He3

### ISSUE THREAD

**Issue by slasdek** [slashlos/He3#13]
Hello!
Right now when I press ctrl+option+cmd He3 hides and mutes any sound that currently running on MacOS. 
It would be great if you could change or disable it.
Thanks

**Comment by slashlos** [comment]
Yes, it's a work in progress as affecting a WkWebView is currently a closed system to programmatic changes.

**Comment by slashlos** [comment]
The user idea was for a "Quick Quiet", like in a submarine, where all audio is cut as well as video. The design is there but access to the WKWebView is not exposed. Simply put the QQ key sequence would be sent to each document to toggle.

Stay tuned...

**Comment by slashlos** [comment]
Ok, testing what appears to be working, injecting a script to each window, which is what I had set out for initially.

It will appear in of 1.0.6, build **8421** and beyond.
