### ISSUE TITLE
Helium isn't moveable on screen

### ISSUE THREAD

**Issue by majomista** [slashlos/He3#20]
I can't move the Helium window around on my desktop. I can resize but not drag it. Any ideas please?
MAC OS Ventura 13.2.1

**Comment by majomista** [comment]
Update: it only moves if you hold pointer over "Above all else', you can't just drag the window around from any point.

**Comment by merche8371** [comment]
Hola Santiago el programa funciona bárbaro pero al actualizar Sonoma ahora al abrirlo se reinicia constantemente Sonomo 14.2.1 es un Mac book pro m2 pro 
[he3.txt](https://github.com/slashlos/He3/files/13924768/he3.txt)

**Comment by merche8371** [comment]
Hello Santiago the program works barbaric but when you update Sonoma now when you open it it constantly restarts Sonomo 14.2.1 is a Mac book pro m2 pro

**Comment by slashlos** [comment]
Hi, not sure what you're meaning; btw windows can be moved if a titlebar was made visible or by holding down CMND during drag of window contents.

**Comment by slashlos** [comment]
Hi, not sure what you're meaning; btw windows can be moved if a titlebar was made visible or by holding down CMND during drag of window contents.

**Comment by slashlos** [comment]
I suggest the help text as window movement has not changed.

**Comment by merche8371** [comment]
Directly does not open the program uninstall it and install it SRL's from the Apple store but when double-clicking as I did before it does not open and the window comes out to send the error information that is the txt that I sent you
