### ISSUE TITLE
allow webcam access

### ISSUE THREAD

**Issue by jochmann** [slashlos/He3#3]
I was trying to use Helium as a floating webcam image for screen recording. Much like the abandoned [CamDesk](http://michaelsboost.com/CamDesk/) I want to create a simple web app where I see a preview of me in my webcam (and some graphics gizmos), but I need a way to display this image in a floating window.

Helium would be awesome for this purpose. It has taken care of the difficult issue of keeping an app window afloat - but it lacks the permissions to display the webcam. Is this feasible to add?

**Comment by slashlos** [comment]
Currently investigating; might be a permission issue but the webcam is not local, but intesting. I favor Nest products so I'll try using that if possible unless you can provide a sample, public URL etc - I can play test with, thanks.

**Comment by jochmann** [comment]
I'm currently running a local html+js combo (lifted from https://github.com/michaelsboost/CamDesk) and run from file:// with my onboard webcam (Macbook).

I have tested a request from https on obs.ninja where "add my camera to OBS" opens a webcam request. He3 throws an error dialog:
"An error has occured when trying to access the webcam or microphone. The reason is not known."

**Comment by slashlos** [comment]
Well, if it's a simple entitlement requirement, I'll try first to add that support to the preferences panel...

**Comment by jochmann** [comment]
a reproducer? I'm not sure what you mean. You can go to https://obs.ninja via He3 and click on the panel to "add your camera to OBS" to reproduce the issue, as I said. Or hand off from Safari from the same site, also generating an error.

**Comment by slashlos** [comment]
Hmm, I might be late to the party but https://bugs.chromium.org/p/chromium/issues/detail?id=752458#c31 suggest Apple has some work todo...

**Comment by slashlos** [comment]
Btw, testing with camera/mic entitlements do not fare better so perhaps something else  - Apple? is needed here.

**Comment by jochmann** [comment]
The bug report forums don't give me much hope, unfortunately. https://bugs.webkit.org/show_bug.cgi?id=208667

**Comment by slashlos** [comment]
Ah that's iOS. Won't help he3.

**Comment by slashlos** [comment]
Unlike webView predecessor, some things are not there or able in the (new) WkWebView but hoping for an opening at some point.

**Comment by jochmann** [comment]
I've created a single-use web app to get around the problem. It uses the browser API for picture in picture mode. Don't know if this is relevant to your needs or if you like the "hack" we used: mirror the feed on a canvas element that we can manipulate. https://pipfy.pxi.gmbh
