### ISSUE TITLE
Purple border color

### ISSUE THREAD

**Issue by Cygnusfear** [slashlos/He3#5]
He3 seems to suffer from a strange purple border. Would be nice to get rid of it.

<img width="572" alt="Screenshot 2020-12-18 at 10 37 09" src="https://user-images.githubusercontent.com/2925132/102605306-fe85bf80-411c-11eb-87d9-a95912517407.png">

**Comment by Cygnusfear** [comment]
Somehow it just disappeared. Fixed I guess 😂

**Comment by Cygnusfear** [comment]
Ok, it occasionally appears again. Would be nice to not have that issue 🚀

**Comment by slashlos** [comment]
Yeah, it's nod to the window's drag state - dragging something into the view will lite it, kinda a visual handle bar.

The intent was to give a visual cue *while dragging* into the view.

Fixed post build 8418 - "might" make it to 1.0.4 in review.

**Comment by paulmist** [comment]
I've got this too. Would definitely prefer not to have it.

Would be nice to have non-rounded corners on the window as a whole too but not sure what's possible.
