### ISSUE TITLE
Creating new tabs

### ISSUE THREAD

**Issue by andredaddo** [slashlos/He3#6]
Hi the browser is awesome!!
I’m just wondering if it is possible to create new tabs inside the browser without having to open new windows.
Thank you very much!

**Comment by andredaddo** [comment]
Also I wanted to know if there is a shortcut to show all tabs, thanks.

**Comment by slashlos** [comment]
Yeah %T was taken (translucency) but OPTN-CMND-N will do it

**Comment by slashlos** [comment]
The menu UIs needed a fix - in build 8420; the way for a new tab is OPTN %N and incognito tab SHFT+OPTN %N.

This should appear in 1.0.6
