### ISSUE TITLE
Request: black and white icon in the menu bar

### ISSUE THREAD

**Issue by pretzelmonster** [slashlos/He3#8]
Hi, I like Helium and it works great for me. 
The only thing that is (visually) annoying is that it's the only coloured icon in my menu bar. 
Can you please add a setting to maybe switch between blue and b/w color?
That would be highly appreciated!

Best regards!

![Menu bar](https://user-images.githubusercontent.com/10651560/107045055-5eb3ec00-67c5-11eb-90da-676bbaad4db5.jpg)

**Comment by slashlos** [comment]
Which version?  latest via app store adopts apple's UI and not much I can can do to affect that. This gets further complicated with light/dark/auto mode.

**Comment by pretzelmonster** [comment]
Hi, it's the latest He3 version from the App Store.
Other apps, e.g. NextCloud have a setting for "monochrome icon" in the menu bar, so I doubt it's automatic with the UI settings.

Thanks for considering this change!

Best regards, Tim.

**Comment by pretzelmonster** [comment]
Hi, I found a tool to hide a few icons I don't need so much (including He3) behind an arrow in the menu bar, so no priority to change HE3 any more.

Thanks anyway!

**Comment by slashlos** [comment]
In 1.0.6 (build 8421+) is a new defaults preference you can clear to get (mostly) black and white icon; I say mostly as white itself didn't come across that well and we alternate based on current appearance.  So

```
1% defaults read -app He3 colorStatusIcon
1
1% defaults write -app He3 colorStatusIcon 0
1% defaults read -app He3 colorStatusIcon
0

```

**Comment by pretzelmonster** [comment]
Thanks! You’re the best!
